// Generated by CoffeeScript 1.11.1
var OpenGraph;

OpenGraph = (function() {
  function OpenGraph() {}

  return OpenGraph;

})();

module.exports = OpenGraph;

//# sourceMappingURL=OpenGraph.js.map
