// Generated by CoffeeScript 1.11.1
var Api, Database, Router, SeqFixtures, Sequelize;

Sequelize = require('sequelize');

SeqFixtures = require('sequelize-fixtures');

Database = require('../database/Database');

Router = require('../requests/Router');

module.exports = Api = (function() {
  function Api(app, cb) {
    var sync;
    this.app = app;
    this.cb = cb;
    this.config = {
      path: __dirname + "/../../api"
    };
    this.db = new Database(this.app);
    this.app.api = Router.getModules(this.config.path, this.db, this.app);
    this.models = this.app.api.models;
    this.fixtures = this.app.api.fixtures;
    this.loadModels();
    sync = this.db.instance.sync();
    sync.then((function(_this) {
      return function() {
        _this.loadFixtures();
        Router.getRoutes(_this.config.path, _this.app, Sequelize, _this.db);
        _this.app.logger.info('✓ '.bold.green + 'Rest API started.');
        return _this.cb();
      };
    })(this));
  }

  Api.prototype.loadModels = function() {
    var m, results;
    results = [];
    for (m in this.models) {
      if (typeof this.models[m].associate === 'function') {
        results.push(this.models[m].associate(this.models));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  Api.prototype.loadFixtures = function() {
    var f, results;
    results = [];
    for (f in this.fixtures) {
      this.app.logger.info('✓ '.bold.green + 'Loaded fixtures for model : %s.', f);
      results.push(SeqFixtures.loadFixtures(this.fixtures[f], this.models));
    }
    return results;
  };

  return Api;

})();

//# sourceMappingURL=Api.js.map
