// Generated by CoffeeScript 1.11.1
var logger, moment, winston;

winston = require('winston');

moment = require('moment');

moment.locale('fr');

winston.cli();

logger = new winston.Logger({
  transports: [
    new winston.transports.Console({
      timestamp: function() {
        return moment().format('DD-MM-YYYY HH:mm:ss');
      }
    })
  ]
});

logger.cli();

module.exports = logger;

//# sourceMappingURL=Logger.js.map
