// Generated by CoffeeScript 1.11.1
var Database, Sequelize;

Sequelize = require('sequelize');

module.exports = Database = (function() {
  function Database(app) {
    this.app = app;
    if (this.app.logger) {
      this.app.logger.info('✓ '.bold.green + 'Selected new database : %s.', this.app.config.db.dev.database);
    }
    return {
      instance: new Sequelize(this.app.config.db.dev.database, this.app.config.db.dev.user, this.app.config.db.dev.password, {
        logging: false,
        dialect: this.app.config.db.dev.adapter,
        dialectOptions: {
          charset: 'utf8mb4'
        },
        define: {
          timestamps: true,
          charset: 'utf8',
          collate: 'utf8_general_ci'
        }
      }),
      sequelize: Sequelize
    };
  }

  return Database;

})();

//# sourceMappingURL=Database.js.map
