// Generated by CoffeeScript 1.11.1
var Security, expressAcl, pathToRegexp;

pathToRegexp = require('path-to-regexp');

expressAcl = require('express-acl');

Security = (function() {
  function Security(app) {
    this.app = app;
    this.config = {
      exclude: {
        path: ['/', '/locales', pathToRegexp('/.well_known/acme-challenge/'), pathToRegexp('/locales/:code'), '/users/auth', '/users/logout', '/users/register', '/users/recover']
      }
    };
    expressAcl.config({
      baseUrl: '/'
    });
    this.app.use(expressAcl.authorize.unless(this.config.exclude));
    this.app.use((function(_this) {
      return function(req, res, next) {
        res.setHeader('Application-Name', _this.app.config.name);
        res.header('Access-Control-Allow-Origin', '*');
        res.header('Access-Control-Allow-Headers', 'X-Requested-Width');
        res.header('Access-Control-Allow-Headers', 'Content-Type');
        res.header('Access-Control-Allow-Methods', 'PUT, GET, POST, DELETE');
        return next();
      };
    })(this));
    this.app.logger.info('✓ '.bold.green + 'Loaded users permissions.');
  }

  return Security;

})();

module.exports = Security;

//# sourceMappingURL=Security.js.map
