// Generated by CoffeeScript 1.11.1
var SocketManager;

SocketManager = (function() {
  function SocketManager(manager) {
    this.clients = manager.clients;
    this.fields = ['id', 'firstname', 'lastname', 'role', 'email_md5', 'status'];
  }

  SocketManager.prototype._getFields = function(data) {
    var client, f;
    client = {};
    for (f in data.user) {
      if (this.fields.indexOf(f >= 0)) {
        client[f] = data.user[f];
      }
    }
    return client;
  };

  SocketManager.prototype.getClientBySocketId = function(id) {
    var s;
    for (s in this.clients) {
      if (this.clients[s] && this.clients[s].id === id) {
        return this._getFields(this.clients[s]);
      }
    }
    return null;
  };

  SocketManager.prototype.getClientSocket = function(id) {
    var s;
    for (s in this.clients) {
      if (this.clients[s] && this.clients[s].user.id === id) {
        return this.clients[s];
      }
    }
    return null;
  };

  SocketManager.prototype.getClient = function(id) {
    var s;
    for (s in this.clients) {
      if (this.clients[s] && this.clients[s].user.id === id) {
        return this._getFields(this.clients[s]);
      }
    }
    return null;
  };

  SocketManager.prototype.getClients = function() {
    var clients, s;
    clients = [];
    for (s in this.clients) {
      if (this.clients[s]) {
        clients.push(this._getFields(this.clients[s]));
      }
    }
    return clients;
  };

  return SocketManager;

})();

module.exports = SocketManager;

//# sourceMappingURL=SocketManager.js.map
