// Generated by CoffeeScript 1.11.1
var Event;

Event = (function() {
  function Event() {}

  Event.prototype.on = function(type, cb) {
    return this['_on' + type] = cb;
  };

  Event.prototype.emit = function(type, data) {
    return this['_on' + type](data);
  };

  return Event;

})();

module.exports = Event;

//# sourceMappingURL=event.js.map
