// Generated by CoffeeScript 1.11.1
var Cluster, Events, Manager, Master, Worker;

Cluster = require('cluster');

Events = require('./Events/Events');

Manager = require('./Manager');

Worker = require('./Worker');

Master = (function() {
  function Master(options) {
    var worker;
    this.options = {
      port: options.port || 5002,
      managerDelay: options.managerDelay || 10,
      workerDelay: options.workerDelay || 150,
      workers: options.workers || 'auto'
    };
    this.manager = new Manager(this.options);
    this.events = new Events(this.manager, this.options);
    if (Cluster.isMaster) {
      this.manager.start();
      this.events.listen();
    } else {
      worker = new Worker(this.options);
    }
  }

  Master.prototype.start = function() {};

  return Master;

})();

module.exports = Master;

//# sourceMappingURL=Master.js.map
