// Generated by CoffeeScript 1.11.1
var Events;

Events = (function() {
  function Events(manager, options) {
    this.manager = manager;
    this.options = options;
    this.io = require('socket.io')();
  }

  Events.prototype.listen = function() {
    this.io.listen(this.options.port);
    return this.io.on('connection', (function(_this) {
      return function(socket) {
        socket.emit('started');
        socket.on('stop', function() {
          return _this.stop();
        });
        socket.on('getWorkers', function() {});
        return socket.on('job', function(job) {
          return _this.manager.queue.push(1, job);
        });
      };
    })(this));
  };

  return Events;

})();

module.exports = Events;

//# sourceMappingURL=Events.js.map
