// Generated by CoffeeScript 1.11.1
var Renderer, _;

_ = require('lodash');

Renderer = function(config) {
  this.render = (function(_this) {
    return function(req, res, next) {
      var render;
      render = res.render;
      res.render = function(view, locals, cb) {
        var settings;
        settings = {
          f_dateY: function() {
            return function() {
              return new Date();
            };
          },
          f_ucfirst: function() {
            return function(str) {
              return _.upperFirst(str);
            };
          }
        };
        return render.call(res, view, _.merge(settings, locals), cb);
      };
      return next();
    };
  })(this);
  return this;
};

module.exports = Renderer;

//# sourceMappingURL=Renderer.js.map
