// Generated by CoffeeScript 1.11.1
var Tokens, expressJwt, pathToRegexp;

expressJwt = require('express-jwt');

pathToRegexp = require('path-to-regexp');

module.exports = Tokens = (function() {
  function Tokens(app) {
    this.app = app;
    this.config = {
      jwt: {
        secret: this.app.config.jwt_secret,
        requestProperty: 'decoded'
      },
      exclude: {
        path: ['/', '/locales', pathToRegexp('/.well_known/acme-challenge/'), pathToRegexp('locales/:code'), pathToRegexp('/domains'), pathToRegexp('/domains:id'), '/users/auth', '/users/logout', '/users/register', '/users/recover']
      }
    };
    this.app.use(expressJwt(this.config.jwt).unless(this.config.exclude));
    this.app.use((function(_this) {
      return function(err, req, res, next) {
        if (err.name === 'UnauthorizedError') {
          return _this.app.error(res, {
            statusCode: 403,
            message: 'Invalid Access-Token'
          });
        }
      };
    })(this));
    this.app.logger.info('✓ '.bold.green + 'Setup JSON Web Tokens.');
  }

  return Tokens;

})();

//# sourceMappingURL=Tokens.js.map
