// Generated by CoffeeScript 1.11.1
var Locales, fs, glob, path;

fs = require('fs');

path = require('path');

glob = require('glob');

module.exports = Locales = (function() {
  function Locales(app) {
    this.app = app;
    this.app.get('/locales/:code', (function(_this) {
      return function(req, res) {
        var lang;
        lang = __dirname + "/../../locales/" + req.params.code + ".json";
        return fs.readFile(lang, 'utf8', function(err, data) {
          if (err === null) {
            return _this.app.success(res, JSON.parse(data).app);
          } else {
            return _this.app.error(res, {
              statusCode: 404,
              message: 'Lang not found'
            });
          }
        });
      };
    })(this));
    this.app.get('/locales', (function(_this) {
      return function(req, res) {
        var dir;
        dir = __dirname + "/../../locales";
        return glob(dir + "/*.json", {}, function(err, files) {
          var langs;
          if (err === null) {
            langs = {};
            files.forEach(function(file) {
              var data, lang;
              lang = path.basename(file, '.json');
              data = fs.readFileSync(file, 'utf8');
              return langs[lang] = JSON.parse(data).app;
            });
            return _this.app.success(res, langs);
          }
        });
      };
    })(this));
    this.app.logger.info('✓ '.bold.green + 'Locales loaded.');
  }

  return Locales;

})();

//# sourceMappingURL=Locales.js.map
